---
title: "ST5209/X Assignment 4"
format: pdf
editor: visual
author: "Due 1 Apr, 11.59pm"
---

## Set up

1.  Make sure you have the following installed on your system: $\text{\LaTeX}$, R4.2.2+, RStudio 2023.12+, and Quarto 1.3.450+.
2.  Pull changes from the course [repo](https://github.com/yanshuotan/st5209-2024).
3.  Create a separate folder in the root directory of the repo, label it with your name, e.g. `yanshuo-assignments`
4.  Copy the assignment1.qmd file over to this directory.
5.  Modify the duplicated document with your solutions, writing all R code as code chunks.
6.  When running code, make sure your working directory is set to be the folder with your assignment .qmd file, e.g. `yanshuo-assignments`. This is to ensure that all file paths are valid.[^1]

[^1]: You may view and set the working directory using `getwd()` and `setwd()`.

## Submission

1.  Render the document to get a .pdf printout.
2.  Submit both the .qmd and .pdf files to Canvas.

```{r}
#| message: FALSE
#| echo: FALSE
library(tidyverse)
library(fpp3)
```

## 1. AR polynomial

Consider the AR(2) model $$
X_t = 4 + 0.5 X_{t-1} - 0.25 X_{t-2} + W_t.
$$ {#eq-ar2}

a.  What is the autoregressive polynomial?

b.  What are its roots?

c.  Is this model causal? Why?

d.  What is the period of the sinusoidal portion of its ACF?

e.  Given the representation $$
    X_t = \sum_{j=0}^\infty \psi_j W_{t-j},
    $$ solve for $\psi_0, \psi_1, \psi_2, \psi_3$.

## 2. Likelihood

Consider the AR(1) model $$
X_t = 1-0.6X_{t-1} + W_t,
$$ where $W_t \sim WN(0, 0.25)$ is Gaussian white noise. We are given observations $x_1 = 0.2, x_2 = -0.3, x_3 = 0.4$.

a.  What is the mean of $X_t$?

b.  Write the full likelihood of this model.

c.  Write the conditional likelihood of this model, when conditioning on the value of $x_1$.

## 3. Reversibility

a.  Create a sample trajectory of length $n = 200$ from the AR(2) model from Problem 1 using `arima.sim()`.

b.  Reverse the time index of the vector you obtain using `rev()`.

c.  Fit an AR(2) model to the reversed time series using `fable`. Hint: You may use the code snippet `model(AR(X ~ order(2)))`.

d.  Inspect the model parameters using `tidy()`. Why are they similar to the those in @eq-ar2?

e.  Make a forecast with $h = 10$. What does this correspond to in terms of the original time series?

## 4. Yule-Walker

a.  Write the Yule-Walker equations for the AR(2) model from Problem 1.

b.  Arrange the equations in the following matrix form (i.e. fill in the missing entries): $$
    \left[\begin{matrix}     ? & ? & ?  \\ ? & ? & ? \\
    ? & ? & ?
    \end{matrix}\right] \left[\begin{matrix}     \gamma(0) \\ \gamma(1) \\ \gamma(2)
    \end{matrix}\right] = \left[\begin{matrix}     \sigma^2 \\ 0 \\ 0
    \end{matrix}\right].
    $$

c.  Solve the system from part b) for $\gamma(0), \gamma(1), \gamma(2)$ numerically using `solve()`.

d.  Given $$
    \Gamma_2 = \left[\begin{matrix}     \gamma(0) & \gamma(1) \\ \gamma(1) & \gamma(0)
    \end{matrix}\right],
    $$ what is the top left entry of $\Gamma_2^{-1}$ in terms of $\gamma(0)$ and $\gamma(1)$?

e.  Write a 95% confidence interval for $\phi_1$ using your answers for d) and 3d).

## 5. Real data analysis

a.  Load the dataset `astsa::globtemp` and convert it into a tsibble.

b.  Filter the time series to include measurements only up to 1960.

c.  Fit an AR model using `model(AR(X))`.

d.  What is order of the model selected? What are the fitted parameters?

e.  Inspect the model residuals using `gg_tsresiduals()`. What can you say about the model fit?
